### ISSUE TITLE
Config value: literal or function

### ISSUE THREAD

**Issue by rucciva** [sematext/logagent-js#135]
As a logstash user, one thing attract me the most to logagent is this statement:

> It is like Filebeat and Logstash in one, without the JVM memory footprint.

I especially love that i can define inline filter in the form of javascript so i can achieve greater flexibility in manipulating the event, since it use javascript function which is far more popular and powerful than logstash syntax. So i would realy love to see whether i can replace my logstash instance with logagent. 

But one thing i find lacking in logagent is the fact that logstash configuration can includes conditional, not only in the filter section. This is helpful especially in routing the output based on the data being processed, not just based only on the sourceName or limited to whatever the plugin want it to be. 

Meanwhile In the case of logagent, i think the use of yaml file have potentials to be more powerful than logstash configuration, since yaml is more popular and the value of the yaml can includes function (moreover in javascript language)

So, I propose that logagent plugins or filter can receive configuration object that holds literal value or function. This way, each time logagent plugins or filters needs to process event, they need to produce a new config object that contain only literal value by iterating the config keys and check wether its value is a type of function or not. The producing of the new config value can be extracted to a separated module, so that the code changes are minor. The function signature could  resemble the inline filter declaration without the eventemitter and callback object

For example:

```yaml
input: 
  kafka: 
    module: logagent-input-kafka
    host: kafka-host
    port: 9092
    groupId: docker-logger-logagent
    topic: docker-filebeat-logs
    autoCommit: true
    sessionTimeout: 15000

output: 
  elasticsearch: 
    module: elasticsearch
    url: !!js/function >
       function (context, config, data) {
           if (data.docker.container.name == "container-a") {
                return "http://a.elasticsearch.local"
           } else {
                return "http://b.elasticsearch.local"
           }
       }
```
