### ISSUE TITLE
Support Kubernetes annotatations for log routing

### ISSUE THREAD

**Issue by megastef** [sematext/logagent-js#165]
At the moment logagent supports only docker container labels and environment variables to set variables for log routing: 
- LOGS_ENABLED / LOGSENE_ENABLED
- LOGS_TOKEN / LOGSENE_TOKEN

Logagent should support Kubernetes pod annotations as well, e.g.: 

```
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    com.sematext.logs.enabled: true
    com.sematext.logs.token: "YOUR_LOGS_TOKEN_FOR_NGINX__HERE"
spec:
  containers:
  - name: nginx
    image: nginx
``` 

Todo: 
- Watch Kubernetes pod deployments 
- Extract pod annotations `com.sematext.logs.enabled` & `com.sematext.logs.token`
- Map annotations to all pod containers
- Use pod annotations for container log routing 

Potential limitations:
- Log routing to different indices for each container would not be possible. 
  E.g. Running MySQL and Nginx in one pod, would not allow to route 
  MySQL and Nginx logs to different Sematext Apps (or Elasticsearch indices) because annotations are per pod and not per container.
