### ISSUE TITLE
Implement plugin for reading from UNIX socket

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#176]

**Comment by megastef** [comment]
You can pipe data in your terminal `netcat -U /var/log/suricata/eve.socket  | logagent --yaml -url https://logsene-receiver.sematext.com -i YOUR_LOGS_TOKEN`

If you run Logagent as service you might prefer to use the [command plugin](https://sematext.com/docs/logagent/input-plugin-command/) together with `netcat` or `socat` to pipe data into Logagent. 

```yml
input:
  # read Suricata EVE log from UNIX socket
  suricata: 
    module: command
    command: netcat -U /var/log/suricata/eve.socket 
    # command: socat UNIX-CONNECT:/var/log/suricata/eve.socket 
    sourceName: suricata
    # time in seconds to repeat the command
    restart: 0
```
