### ISSUE TITLE
common log format error

### ISSUE THREAD

**Issue by nravi89** [sematext/logagent-js#3]
burger.letters.com - - [01/Jul/1995:00:00:12 -0400] "GET /shuttle/countdown/video/livevideo.gif HTTP/1.0" 200 0

the ip of type burger.letters.com is not getting parsed correctly

**Comment by megastef** [comment]
Which Docker Container do you use?

**Comment by megastef** [comment]
In any case here is pattern you need:

```yml

- #  Web Logs
  sourceName: !!js/regexp /httpd|access_log|apache2|nginx/
  match:
    - regex: !!js/regexp /^(\S+)\s+(-|.+?)\s+(-|.+?)\s+\[(.*)\]\s\"(\S+)\s(\S+)\s(\S+)\s(\d+)\s(\d+)/i
      type: access_common
      fields:       [client_ip,remote_id,user,ts,method,path,http_version,status_code,size]
      dateFormat: DD/MMM/YYYY:HH:mm:ss ZZ
      transform: !!js/function >
        function (p) {
          p.message = p.method + ' ' + p.path
        } 

```
