### ISSUE TITLE
Aggregate or down-sample events

### ISSUE THREAD

**Issue by erik-stephens** [sematext/logagent-js#40]
In order to relieve pressure downstream and to avoid collation complexity, would be nice if I could aggregate logs within logagent-js.  I'll try to explain more with an example.  I would like logs such as:
```
{message: 'foo happened', field1: 'type1', metric1: 42, metric2: 1}
{message: 'foo happened', field1: 'type2', metric1: 24, metric2: 2}
{message: 'foo happened', field1: 'type1', metric1: 40, metric2: 3}
```

to be user-definably aggregated with something like the following before shipping them:
```
function aggregateFoo(pattern, buffer) {
  if (buffer.foo === undefined) {
    buffer.foo = {};
  }
  if (buffer.foo[pattern.field1] == undefined) {
    buffer.foo[pattern.field1] = {metric1: [], metric2: [], first: now()};
  }
  var agg = buffer.foo[pattern.key];
  agg.metric1.push(pattern.metric1);
  agg.metric2.push(pattern.metric2);
  agg.last = now();
  // Could aggregate in N-minute minimum buckets
  if (agg.last - agg.first > '5 minutes') {
    shipFoo(agg);
  }
  // Could aggregate once N samples collected
  if (agg.metric1.length > 100) {
    shipFoo(agg);
  }
  delete buffer.foo;
}

function shipFoo(agg) {
  // Demonstrating how users may want to define the aggregated event.
  var event = {};
  event.message = 'foo happened ' + agg.metric1.length + ' times';
  event.ts = agg.last;
  event.window = agg.last - first;
  event.metric1 = avg(agg.metric1);
  event.metric2 = max(agg.metric1);
  ship(event);
}
```

Is this already on the road map, and if not, is it in the scope of what you would like for logagent-js?  I may have the green light to hack my way through this.  If could be generally useful to others, let's discuss further here on how best to approach?

**Comment by megastef** [comment]
+1 nice!

**Comment by otisg** [comment]
Looks useful at first glance.  One may want to know the exact time window from which these aggregations were derived (so 'from' and 'to' timestamps may need to be tracked and simply shipped as fields).

Logagent now has support for pluggable inputs and outputs.  Would this be an output, or would it be better to be able to allow pluggable "processors" (the stuff between inputs and outputs)?

**Comment by megastef** [comment]
My questions:
1. Is this a parser feature to aggregate messages? Then it would work for all tools using the parser. 
    No need to change current workflow. 
2. Is this a logs shipper feature, then it needs to be a pluggable "processor". Currently we have only input and output plugins. Inputs emit "data.raw" events, LA does paring and emits then "data.parsed" events. Output plugins listen to "data.parsed".  A "filter/processor plugin" needs to run before "data.parsed" is emitted -> little change in the framework.

**Comment by erik-stephens** [comment]
@otisg, I think the stuff between.  Plus, there's state to manage, which probably makes this a bit more complicated than an input or output.  Regarding which fields to ship, my hope is that could be completely defined by the user since I expect many different use cases.

@megastef, not sure I know enough to answer.  Now that #22 is complete, I think I can define my filter() to drop the event if my transform() marked it as aggregated.  I think all I may need is some temporary buffer space to store the relevant bits of the event.  Does it make sense to use the pattern object for that or would that be too kludgy?  My transform() would need access to it in order to return the aggregated event as desired (eg time, count).  That would be my naive way of going about it.

**Comment by megastef** [comment]
Well using #22 is something which would work in the "user land". Setting pattern.aggBuffer or pattern.aggTimer. The pattern object gets only destroyed when the patterns.yml changes (hot-reload).

I think we need filter plugins in any case and it would be the best place for aggregation, before data is passed to output plugins. A simple default could just load a JS function (inline in config) or from a JS file/module.

**Comment by megastef** [comment]
@erik-stephens I think this is what are looking for. https://www.npmjs.com/package/logagent-filter-output-sql. This outputFilter plugin provides SQL based queries to filter or aggregate log events (already parsed by patterns applied before ...).

**Comment by erik-stephens** [comment]
Very cool!  Quickly scanned the source of that plugin.  The buffer is flushed based on configured interval?  So if I set interval to 300, it will buffer all events for past 5 minutes and flush the buffer?  That should work nicely for our needs.

If haven't thought about it yet, might want to consider what is expected behavior if user feeds it a bad query.  If it's possible for the [query to raise an exception](https://github.com/megastef/logagent-filter-output-sql/blob/20a4fbea9c9bdd20aa987cf85ec09abbdc619a93/index.js#L22), then buffer might blow up.  Also, looks like buffer will continue to grow if query returns no results.  I would expect buffer to be flushed in that case as well.

**Comment by megastef** [comment]
Yes, the interval is configurable (value in seconds). Please note that the buffer keeps all records for this time in memory (e.g. 5 minutes in your example). All SQL operations are currently in-memory and the required memory for logagent grows with the number of buffered events until the SQL queries are executed. 

Fixed error handling https://github.com/megastef/logagent-filter-output-sql/commit/ce9b45f8ee0d20848547c9083a610d60c47b943b

Thanks for the great feedback.

**Comment by erik-stephens** [comment]
Apologies if I'm mis-reading the code, but I think makes sense to still emit data.parsed with an empty list when query returns no results - looking at the `return if (result && result.length === 0)` bit.  As a user of this functionality, I may want to emit that aggregation as a zero event.  Plus, looks like buffer could still grow unbounded if my query never matches any events.  Over all I think this is great, so feel free to close this issue if happy with it - don't want you to feel like have to wait for my "blessing".

**Comment by erik-stephens** [comment]
Tested the sql output plugin.  One bit I'm missing is how to process the results of the plugin - still needing some user-defined javascript to fill the gaps that alasql leave for our use cases.  I'd like it emitted back up the stream somewhere besides where emit(`data.parsed`) takes it.  I don't think `data.raw` makes sense all the time either which has me wondering if there are plans for letting users configure the processing pipeline.  I'm wondering if a distinction needs to be made between input filters, processors, and output filters as mentioned in #43 and instead let processors subscribe to msgs and publish them on specific channels.  I'm using the term "channel" but I think as simple as the event name to subscribe (`on()`) & publish (`emit()`) to.  Spit-balling my ideal setup:

- I define an input and specify the channel to emit to, let's say `my.foo`.  The default could be `data.raw` to preserve current behavior.
- I define a sql filter to process msgs on a channel `my.foo` and emit the processed msg to channel `my.bar`.
- I define a user-defined function filter for msgs on channel `my.bar`.  Maybe I drop the msg, maybe I perform some side-effect and emit the msg unmodified, maybe I modify the msg.  For this specific example, let's say I emit it to channel `my.elasticsearch`.
- My elasticsearch output filter is configured to index msgs on `my.elasticsearch`.  The default channel could be `data.parsed` to preserve current behavior.

If it's as simple as I think it is, I could come up with a PR.  Wanted to gauge where y'all are on this before diving in.  Maybe have other plans or see problems with this approach?

**Comment by megastef** [comment]
@erik-stephens This is a very good suggestion. Please tell us about:

```One bit I'm missing is how to process the results of the plugin - still needing some user-defined javascript to fill the gaps that alasql leave for our use cases.```

We have not documented latest Elasticsearch output features like routing logs to different servers/indicies. 

What you describe above is exactly the initial idea we had for "Event based architecture". 
Down the road it was was not so easy or is not completed:
- We used initially https://github.com/asyncly/EventEmitter2 to have wildcard events, but for performance reasons we moved back to default EventEmitter 
- What you describe above requires to make "listen" and "emit" event names configurable for all existing plugins - this was simply not done (one could say incomplete move to new architecture) and I think it is not much work to add it to all existing input/output plugins (not that many ...). The logagent parser is currently a central functions, where all data flows through and this might needs to be changed to hook it into custom event processors. 
- Using the "event channels" will create more events than we need - 100k logs might generate 600k or more events at least this was one of my considerations for resource foot print
- Input/Output Filters are a bit different than input/output plugins. Filters (including transforms) must  be "serialized" and we decided for generator functions called in "serial" way.  Connecting multiple filters will need configuration for N listen and emit event names - at this point my opinion was it would be too complicated for regular users to understand this. 

We are open for good suggestion or PR and we like to improve the usability and reduce JS programming parts for the end users. 

Just to complete the current status, we can have workflows like this: 
````
Input File
  - watch files by GLOB patterns
  - emit 'data.raw' new lines from each changed file with a context having source name
  -> Apply N Input Filter (e.g. Grep filter)
    - match source name from 'context'
    - drop | emit depending on 'data' or source
      -> Parser 
         - match patterns by sourceName from context
         - match regex / parse structure
         -> Apply N  Output Filter (e.g SQL filter)
            - transform, aggregate, 
            - drop/emit 'data.parsed'
            -> N Output Plugins (e.g. Elasticsearch)
               - listen to 'data.parsed'
               - route to Elasticsearch URL and map source name to URL/indices
                 - match source name by regex 
                 - map to index name (config)

```

An example config might look like this (sorry it might make much sense, but it outlines the options): 
```yaml
input:
  files:
      - '/var/log/**/*.log'
      - '/opt/mylogs/*.log'

inputFilter:
  - module: grep
    config:
      matchSource: !!js/regexp /nginx/
      include: !!js/regexp /.*/i
      exclude: !!js/regexp /OPTIONS/i


outputFilter:
  - module: sql
    config:
      source: !!js/regexp /access.log|httpd|nginx/
      interval: 1
      queries:
        - # calculate average page size for different HTTP methods
          SELECT 'apache_stats' AS _type, 
                  AVG(size) AS size_avg, 
                  COUNT(method) AS method_count, 
                  method as http_method
          FROM ? 
          WHERE method is not null
          GROUP BY method

output:  
  es-secure-local:
    module: elasticsearch 
    url: http://localhost:9200
    httpOptions:
      key: ./client.key
      cert: ./server.crt
      rejectUnauthorized: false
    indices: 
      my_secure_logs_index: 
        - system\.log
        - access\.log
        - auth\.log
        - wifi.log
  logsene-saas:
    module: elasticsearch
    url: https://logsene-receiver.sematext.com
    indices: 
      269d7b2f-0e7d-4e92-ae7f-xxxxxxxxxx: 
        - access.log
        - nginx.log
```
