### ISSUE TITLE
Multiline parsing gets too many lines (at least on Windows)

### ISSUE THREAD

**Issue by radu-gheorghe** [sematext/logagent-js#70]
## Steps to reproduce

Download and install .NET Framework 3.5

Install node: https://nodejs.org/dist/v6.9.2/node-v6.9.2-x64.msi

Install Logagent, the Elasticsearch Stats and the Windows Events plugin:
`npm i -g @sematext/logagent`

Go to `%ProgramData%`, create a folder named Sematext and this to `logagent.conf`:
```
options:
  includeOriginalLine: false
  suppress: true

input:
  files:
      - 'c:\\elasticsearch\\logs\\*.log'

output:  
  logsene:
    module: elasticsearch
    url: https://logsene-receiver.sematext.com
    indices:
      LOGSENE_TOKEN_GOES_HERE:
        - elasticsearch.*log
```

Install the Logagent service (Logagent will start automatically):
`logagent-windows -install`

Do something that produces a number of events (e.g. restart Elasticsearch).

## Actual result

Multiple events are stitched together as one.
