### ISSUE TITLE
[ Dynamic output file name based on field's content with stdout output ]

### ISSUE THREAD

**Issue by jerome83136** [sematext/logagent-js#87]
Hi,

I wonder if I can use logagent-js (because it needs very few resources on the system); to filter my log files.

I want to read some log files (file input) and to write them into several output files based on the content on the input log files.

Example:

My source log file contains apache2 access logs and these lines will be written to the corresponding output files:
"myip1 myuser1 timestamp mycountry1 myapp1 blah" --> output file: /tmp/myapp1_mycountry1.txt
"myip2 myuser2 timestamp mycountry2 myapp1 blah" --> output file /tmp/myapp1_mycountry2.txt

Is there a way to achieve this, by using stdout ouput maybe ?

Thanks for your help

Best regards
Jérôme

**Comment by megastef** [comment]
Hi @jerome83136 - I liked your idea so much that I contributed an output plugin for files, including dynamic file names and log rotation. See an example for the "output-file" plugin usage here: 
https://github.com/sematext/logagent-js/blob/master/config/examples/output-files.yml

We just released the Logagent v2.0.77 on npm including the new plugin. We will update the documentation in the next days. 

You could combine the file-output with the [file input](https://sematext.com/docs/logagent/input-plugin-files/) for your web server logs. Note, you might need to adjust apache log patterns to extract country code. If you provide an example we could help with it. 

In case you like to visualize locations check out Logagent GeoIP feature - the easiest way to get GeoIP data into Kibana is to use [SematextCloud](https://sematext.com/cloud) with the [Elasticsearch output plugin](https://www.sematext.com/docs/logagent/output-elasticsearch/). In case your Apache2 runs in Docker, you might like one of my past blog posts [Automatic Geo-IP Enrichment for Docker Logs](https://sematext.com/blog/2016/04/11/automatic-geo-ip-enrichment-for-docker-logs-2/) or the [detection of malicious traffic in web server logs](https://sematext.com/blog/2017/08/23/how-to-detect-malicious-traffic-in-your-server-logs-sematext-access-watch/) using Logagent.

**Comment by megastef** [comment]
@jerome83136 did the new plugin work for you?

**Comment by jerome83136** [comment]
Hi Stefan;
Glade to see my idea was usefull :)

I will soon give your plugin a try and let you know.

Many thanks for your help

Best regards
Jérôme

2017-09-20 14:04 GMT+02:00 Stefan Thies <notifications@github.com>:

**Comment by jerome83136** [comment]
Hi again,
It's just awesome ! Works great ! Many thanks :)

I don't know if I can; but I have an improvement request: I need to be able to select the output format of the resulting lines written on the output file.
So, is there a way to configure the output format ? It would be great to have something which let me select which fields will be composing the resulting log line written to the output files.

**Example:**

The regex part of the config to extract the fields from the input:

```
regex: !!js/regexp /(.*)\s(.*)\s(.*)\s(.*)/
fields: [ip,user,country,message]
```

The output part of the config, with a section to specify the desired output format:

```
output:
  files:
    module: output-files
    fileName: '/tmp/{country}.txt'
    # available format values: 'ldjson' (default), 'yaml', 'pretty' (pretty JSON), 'plaintext' ??
    format: plaintext (or something else ?)
    outputFields: {ip}, {country}, {message}
    # matches context.sourceName == data.logSource
    sourceName: .*
    # matches data._type field
    typeName: countryInfo
    # properties for https://www.npmjs.com/search?q=rotating-file-stream
    #size: 10M
    maxFiles: 31
    interval: 1d
    compress: true
```

**Example input log lines:**
1.2.3.4 user1 italy /myapp/index.html
1.2.9.10 user2 england /mycontent/register.php

**Resulting output:**
/tmp/itay.txt will contain --> 1.2.3.4 italy /myapp/index.html
/tmp/england.txt will contain --> 1.2.9.10 england /mycontent/register.php

Best regards
Jérôme

**Comment by megastef** [comment]
@jerome83136 please check '@sematext/logagent' release 2.0.82. See commit https://github.com/sematext/logagent-js/commit/14af15efd513e565105765a99d69c29260c3c377
You could specify format 'template" and provide in the configuration property 'template' a template string. 

Example: 

```
output:
  files:
    module: output-files
    fileName: '/tmp/{country}.json'
    # available format values: 'ldjson' (default), 'yaml', 'pretty' (pretty JSON), 'template'
    format: template
    template: '{ip}, {country}, {message}'
    # matches context.sourceName == data.logSource
    sourceName: .*
    # matches data._type field 
    typeName: countryInfo
    # properties for https://www.npmjs.com/search?q=rotating-file-stream
    size: 10M
    maxFiles: 2
    interval: 1d
    compress: true
```
Can we close the issue? 

Thank you for contributing your ideas. I find this feature particularly useful to export data to files from [supported data sources](https://www.sematext.com/docs/logagent/#plugins) like MySQL, Postgres, MS-SQL, Elasticsearch, Logfiles or Kafka topics :)
