### ISSUE TITLE
[ Allow time based naming in output files plugin ]

### ISSUE THREAD

**Issue by jerome83136** [sematext/logagent-js#90]
Hi,
The files ouput plugin is just great; but I need to rotate my files based on the current time (like the elasticsearch output does with indices names)

Is it possible to have the files output plugin naming the output files like this: /tmp/myfile1.{country}-YYYY.MM.DD

Or, even better; is it possible to parse the log line to extract a timestamp and to store it in a arbitrary field ?
The resulting output files configuration would be like:
/tmp/myfile1.{country}-{my-date-field}

Many thanks for your help

Best regards
Jérôme

**Comment by otisg** [comment]
That would be great, @V1shvesh !

**Comment by megastef** [comment]
I think the output file plugin has all options: 

```
config format example:
    output:
      files:
          module: file-output
          format: template #  or ldjson, pretty, yaml
          template: '{fieldA} {fieldB}'
          sourceName: .*
          filename: /tmp/${fieldName}.txt
          size: 10M
          maxFiles: 2
          interval: 1d
          compress: true
```
